### ISSUE TITLE
IdentityServer 4 version 4.x name is vNext in abp 6.x version

### ISSUE THREAD

**Issue by hemiaoio** [Mjollnirs/Abp.ZeroCore.IdentityServer4.Configuration#5]
IdentityServer 4 version 4.x name is vNext in abp 6.x version, it does not for abp.vnext.
Can you push the nuget package to nuget.org?

**Comment by Mjollnirs** [comment]
You can update it, and create pull requests.

**Comment by hemiaoio** [comment]
I was created pull request....but ... you changed it.
https://github.com/Mjollnirs/Abp.ZeroCore.IdentityServer4.Configuration/pull/4
